[translation]
"一些文字" = "Some words"
"含属性的节点" = "Node with attributes"
"说明" = "explanation"
"我" = "I"
"爱" = "Love"
"你" = "You"
"我爱你" = "I Love You"
"{{a}} 加 {{b}} 得到 {{A}}" = "Add {{a}} to {{b}} to get {{A}}"